#!/usr/bin/env python


import json
import subprocess
import os
import sys


def main():
    target_name = sys.argv[1]
    pipeline_name = sys.argv[2]
    pipeline_url = sys.argv[3]

    jobs = json.loads(subprocess.check_output("fly -t {target_name} jobs -p {pipeline_name} --json".format(
        target_name=target_name,
        pipeline_name=pipeline_name,
    ).split(" ")))

    failed_jobs = [
        job
        for job
        in jobs
        if (
                job['finished_build']
                and
                job['finished_build']['status'] != 'succeeded'
                and
                job.get('paused') != True
        )
    ]

    info = []

    for failed_job in failed_jobs:
        sys.stderr.write(json.dumps(failed_job) + "\n")
        info.extend([failed_job['name'], failed_job['finished_build']['status']])

    running_jobs = [job for job in jobs if job.get('next_build') ]
    
    result = {
      "result": len(failed_jobs) == 0,
      "changing": len(running_jobs) > 0,
      "url": pipeline_url,
      "info": info
    }
    print json.dumps(result)

    
main()
