#!/usr/bin/env python


import json
import subprocess
import os
import sys


def main():
    target_name = sys.argv[1]
    pipeline_name = sys.argv[2]
    pipeline_url = sys.argv[3]

    lines = json.loads(subprocess.check_output("fly -t {target_name} jobs -p {pipeline_name} --json".format(
        target_name=target_name,
        pipeline_name=pipeline_name,
    ).split(" ")))

    failed_lines = [line for line in lines if line['finished_build'] and line['finished_build']['status'] != 'succeeded']

    info = []

    for failed_line in failed_lines:
        info.extend([failed_line['name'], failed_line['finished_build']['status']])
    
    result = {
      "result": True,
      "changing": True,
      "url": pipeline_url,
      "info": info
    }

    print json.dumps(result)

    
main()
